WebBanHang/Controllers/LoaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LoaisController : Controller
    {
        private readonly MyDBContext _context;
        private readonly string admin = "Admin";

        public LoaisController(MyDBContext context)
        {
            _context = context;
        }

        // GET: Loais
        public async Task<IActionResult> Index()
        {
            if (User.Identity.Name != admin)
            {
                return RedirectToAction("Index", "TrangChus");
            }
            return View(await _context.loais.ToListAsync());
        }

        // GET: Loais/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loai = await _context.loais
                .FirstOrDefaultAsync(m => m.MaLoai == id);
            if (loai == null)
            {
                return NotFound();
            }

            return View(loai);
        }

        // GET: Loais/Create
        public IActionResult Create()
        {
            if (User.Identity.Name != admin)
            {
                return RedirectToAction("Index", "TrangChus");
            }
            return View();
        }

        // POST: Loais/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaLoai,TenLoai")] Loai loai)
        {
            if (ModelState.IsValid)
            {
                _context.Add(loai);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(loai);
        }

        // GET: Loais/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loai = await _context.loais.FindAsync(id);
            if (loai == null)
            {
                return NotFound();
            }
            return View(loai);
        }

        // POST: Loais/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaLoai,TenLoai")] Loai loai)
        {
            if (id != loai.MaLoai)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loai);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoaiExists(loai.MaLoai))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(loai);
        }

        // GET: Loais/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loai = await _context.loais
                .FirstOrDefaultAsync(m => m.MaLoai == id);
            if (loai == null)
            {
                return NotFound();
            }

            return View(loai);
        }

        // POST: Loais/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var loai = await _context.loais.FindAsync(id);
            _context.loais.Remove(loai);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoaiExists(int id)
        {
            return _context.loais.Any(e => e.MaLoai == id);
        }
    }
}

WebBanHang/Controllers/OdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;
using WebBanHang.Models;
using WebBanHang.ViewModels;

namespace WebBanHang.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OdersController : Controller
    {
        private readonly MyDBContext _context;
        private readonly string admin = "Admin";

        public OdersController(MyDBContext context)
        {
            _context = context;
        }

        // GET: Oders
        public async Task<IActionResult> Index(int page = 1)
        {
            if (User.Identity.Name != admin)
            {
                return RedirectToAction("Index", "TrangChus");
            }
            var query = _context.Oders.AsNoTracking().OrderBy(p => p.ID);
            var model = await PagingList.CreateAsync(query, 10, page);
            return View(model);
        }

        // GET: Oders/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oder = await _context.Oders
                .FirstOrDefaultAsync(m => m.ID == id);

            if (oder == null)
            {
                return NotFound();
            }

            var subOderDetail = await _context.OderDetails.Where(m => m.OderID == oder.ID).ToListAsync();

            if (subOderDetail != null)
            {

                var oderDetail = (from A in _context.HangHoas
                                  join B in subOderDetail on A.MaHH equals B.MaHH
                                  join C in _context.loais on A.MaLoai equals C.MaLoai
                                  select new OrderDetailViewModel
                                  {
                                      ID = B.ID,
                                      TenHH = A.TenHH,
                                      Loai = C.TenLoai,
                                      Quantity = B.Quantity,
                                      GiamGia = A.GiamGia,
                                      Gia = B.Gia,
                                      ThanhTien = Math.Round((B.Gia - B.Gia * A.GiamGia / 100) * B.Quantity, 0)
                                  }
                                     );


                ViewBag.oderDetail = await oderDetail.ToListAsync();
            }

            return View(oder);
        }


        // GET: Oders/Create
        public IActionResult Create()
        {
            if (User.Identity.Name != admin)
            {
                return RedirectToAction("Index", "TrangChus");
            }
            return View();
        }

        // POST: Oders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Status,CustomerID,ShipName,ShipMobile,ShipAddress,ShipEmail,CreatedDate,CheckOutType,Total")] Oder oder)
        {
            if (ModelState.IsValid)
            {
                oder.ID = DateTime.Now.Ticks;
                _context.Add(oder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(oder);
        }

        // GET: Oders/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oder = await _context.Oders.FindAsync(id);
            if (oder == null)
            {
                return NotFound();
            }
            return View(oder);
        }

        // POST: Oders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ID,Status,CustomerID,ShipName,ShipMobile,ShipAddress,ShipEmail,CreatedDate,CheckOutType,Total")] Oder oder)
        {
            if (id != oder.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(oder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OderExists(oder.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(oder);
        }

        // GET: Oders/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oder = await _context.Oders
                .FirstOrDefaultAsync(m => m.ID == id);

            if (oder == null)
            {
                return NotFound();
            }

            var oderDetail = await _context.OderDetails.Where(m => m.OderID == oder.ID).ToListAsync();

            if (oderDetail == null)
            {
                return NotFound();
            }

            var subOrderDetail = (from A in _context.HangHoas
                                  join B in oderDetail on A.MaHH equals B.MaHH
                                  join C in _context.loais on A.MaLoai equals C.MaLoai
                                  select new OrderDetailViewModel
                                  {
                                      TenHH = A.TenHH,
                                      Loai = C.TenLoai,
                                      Quantity = B.Quantity,
                                      Gia = B.Gia,
                                      GiamGia = A.GiamGia,
                                      ThanhTien = (B.Gia - B.Gia * A.GiamGia / 100) * B.Quantity
                                  }
                                 );

            ViewBag.oderDetail = await subOrderDetail.ToListAsync();
            return View(oder);
        }

        // POST: Oders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var oder = await _context.Oders.FindAsync(id);
            var oderDetail = await _context.OderDetails.Where(m => m.OderID == oder.ID).ToListAsync();

            if(oderDetail != null)
            {
                foreach (var item in oderDetail)
                {
                    _context.OderDetails.Remove(item);
                }
            }

            _context.Oders.Remove(oder);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool OderExists(long id)
        {
            return _context.Oders.Any(e => e.ID == id);
        }
    }
}

WebBanHang/Views/Shared/Layout_3.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Free Bootstrap Themes by 365Bootstrap dot com - Free Responsive Html5 Templates">
    <meta name="author" content="http://www.365bootstrap.com">

    <title>@ViewData["Title"]</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/style.css">


    <!-- Custom Fonts -->
    <link rel="stylesheet" href="~/font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/fonts/font-slider.css" type="text/css">

    <!-- jQuery and Modernizr-->
    <script src="~/js/jquery-2.1.1.js"></script>

    <!-- Core JavaScript Files -->
    <script src="~/js/bootstrap.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
    <![endif]-->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-WXECE65Z38"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-WXECE65Z38');
    </script>
</head>

<body>




    <!--Top-->
    <nav id="top">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <select class="language">
                        <option value="Vietnamese" selected>Vietnamese</option>
                        <option value="English" selected>English</option>
                        <option value="France">France</option>
                        <option value="Germany">Germany</option>
                    </select>
                    <select class="currency">
                        <option value="VND" selected>VND</option>
                        <option value="EUR">EUR</option>
                        <option value="USD">USD</option>
                    </select>
                </div>
                <div class="col-xs-6">
                    <ul class="top-link">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a asp-controller="TrangChus" asp-action="Subscribe">
                                    Subscribe for more Products
                                </a>
                            </li>
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <a asp-controller="TrangChus" asp-action="Create">
                                        <span class="glyphicon glyphicon-user"></span> Đăng ký
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="TrangChus" asp-action="Login">
                                        <span class="glyphicon glyphicon-log-in"></span> Đăng nhập
                                    </a>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a asp-controller="AdMin" asp-action="Profile">
                                        Xin chào,
                                        <b>@User.Identity.Name</b>
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="TrangChus" asp-action="Logout">
                                        <span class="glyphicon glyphicon-log-in"></span> Đăng xuất
                                    </a>
                                </li>
                            }
                        </ul>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!--Header-->
    <header class="container">
        <div class="row">
            <div class="col-md-4">
                <div id="logo"><img src="~/images/laptopshop.jpg" /></div>
            </div>
            <div class="col-md-4">
                <form class="form-search">
                    <input type="text" class="input-medium search-query" name="query">
                    <button asp-action="Search" asp-controller="TrangChus" type="submit" class="btn"><span class="glyphicon glyphicon-search"></span></button>
                </form>
            </div>
            <div class="col-md-4">
                <div id="cart"><a class="btn btn-1" asp-action="index" asp-controller="cart"><span class="glyphicon glyphicon-shopping-cart"></span>Giỏ hàng: @ViewBag.quantity item(s)</a></div>
            </div>
        </div>
    </header>
    <!--Navigation-->
    <nav id="menu" class="navbar">
        <div class="container">
            <div class="navbar-header">
                <span id="heading" class="visible-xs">Categories</span>
                <button type="button" class="btn btn-navbar navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"><i class="fa fa-bars"></i></button>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-action="Index" asp-controller="TrangChus">Trang chủ</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sản phẩm</a>
                        <div class="dropdown-menu">
                            <div class="dropdown-inner">
                                <ul class="list-unstyled">
                                    <li>
                                        @foreach (var item in ViewBag.model)
                                        {
                                            <a asp-action="Showsp" asp-route-maloai="@item.MaLoai" asp-controller="TrangChus"> @item.TenLoai</a>
                                        }
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">ABOUT</a>
                        <div class="dropdown-menu">
                            <div class="dropdown-inner">
                                <ul class="list-unstyled">

                                    <a asp-action="GioiThieu" asp-controller="TrangChus"> Giới Thiệu</a>
                                    <a asp-action="DieuKhoan" asp-controller="TrangChus"> Điều Khoản</a>
                                    <a asp-action="ChinhSach" asp-controller="TrangChus"> Chính Sách và Dịch Vụ</a>

                                </ul>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown">
                        <a asp-action="showbaiviet" asp-controller="TrangChus" class="dropdown-toggle" data-toggle="dropdown">Bài viết</a>


                    </li>
                    <li><a asp-action="Contact" asp-controller="TrangChus">CONTACT</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!--//////////////////////////////////////////////////-->
    <!--///////////////////HomePage///////////////////////-->
    <!--//////////////////////////////////////////////////-->

            @RenderBody()

     
    <footer>
        <div class="container">
            <div class="wrap-footer">
                <div class="row">
                    <div class="col-md-3 col-footer footer-1">
                        <img src="~/images/laptopshop.jpg" />
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                    </div>
                    <div class="col-md-3 col-footer footer-2">
                        <div class="heading"><h4>Chăm sóc khách hàng</h4></div>
                        <ul>
                            <li><a href="#">Về chúng tôi</a></li>
                            <li><a href="#">Thông tin giao hàng</a></li>
                            <li><a href="#">Chính sách bảo mật</a></li>
                            <li><a href="#">Các điều khoản và diều kiện</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-footer footer-3">
                        <div class="heading"><h4>Liên kết nhanh</h4></div>
                        <ul>
                            <li><a href="#">Tin tức</a></li>
                            <li><a href="#">Danh sách nhãn hiệu</a></li>
                            <li><a href="#">Chinh sách giảm giá</a></li>
                            <li><a href="#">Mặt hàng ngẫu nhiên</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-footer footer-4">
                        <div class="heading"><h4>Liên hệ</h4></div>
                        <ul>
                            <li><span class="glyphicon glyphicon-home"></span>Ho Chi Minh, Viet Nam </li>
                            <li><span class="glyphicon glyphicon-earphone"></span>+8400 000 0000</li>
                            <li><span class="glyphicon glyphicon-envelope"></span>shop@email.com</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        Your Store © 20xx - <a href="http://www.365bootstrap.com" rel="nofollow" target="_blank">Ecommerce Themes</a> Designed by <a href="http://www.365bootstrap.com" rel="nofollow" target="_blank">365BOOTSTRAP</a>
                    </div>
                    <div class="col-md-6">
                        <div class="pull-right">
                            <ul>
                                <li><img src="~/images/visa-curved-32px.png" /></li>
                                <li><img src="~/images/paypal-curved-32px.png" /></li>
                                <li><img src="~/images/discover-curved-32px.png" /></li>
                                <li><img src="~/images/maestro-curved-32px.png" /></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

WebBanHang/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebBanHang</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="TrangChus" asp-action="Index" class="navbar-brand">WebBanHang</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Loais" asp-action="Index">Loại</a></li>
                    <li><a asp-area="" asp-controller="HangHoas" asp-action="Index">Hàng Hóa</a></li>
                    <li><a asp-area="" asp-controller="HangHoas" asp-action="Search">Tìm Kiếm</a></li>
                    <li><a asp-area="" asp-controller="Oders" asp-action="Index">Order</a></li>
                    <li><a asp-area="" asp-controller="OderDetails" asp-action="Index">Order Details</a></li>
                    <li><a asp-area="" asp-controller="BaiViets" asp-action="Index">Bài Viết</a></li>
                    <li><a asp-area="" asp-controller="Contacts" asp-action="Index">Liên Hệ </a></li>
                    <li><a asp-area="" asp-controller="TaiKhoans" asp-action="Index">User </a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a asp-controller="TaiKhoans" asp-action="Create">
                                <span class="glyphicon glyphicon-user"></span> Đăng ký
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Admin" asp-action="Login">
                                <span class="glyphicon glyphicon-log-in"></span> Đăng nhập
                            </a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a asp-controller="AdMin" asp-action="Profile">
                                Xin chào, 
                                <b>@User.Identity.Name</b>
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Admin" asp-action="Logout">
                                <span class="glyphicon glyphicon-log-in"></span> Đăng xuất
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebBanHang</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>