WebBanHang/Models/HangHoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebBanHang.Models
{
    [Table("HangHoa")]
    public class HangHoa
    {
        [Key]
        public int MaHH { get; set; }
        [Required]
        [MaxLength(100)]
        public string TenHH { get; set; }
        public string Hinh { get; set; }
        public string MoTa { get; set; }
        [Range(0, double.MaxValue)]
        public double DonGia { get; set; }
        [Range(0, int.MaxValue)]

        public int SoLuong { get; set; }
        [ForeignKey("MaLoai")]
        public int MaLoai { get; set; }
        public DateTime NgayDang { get; set; }
        [Required(ErrorMessage = "Không để trống!")]
        [Range(0, 100, ErrorMessage = "Giảm giá từ 0% đến 100% !")]
        public int GiamGia { get; set; }
        public Loai Loai { get; set; }
        public int DaMua { get; set; }
        public bool NoiBat { get; set; }
    }
}

WebBanHang/Controllers/HangHoasController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HangHoasController : Controller
    {
        private readonly MyDBContext _context;
        private readonly string admin = "Admin";

        public HangHoasController(MyDBContext context)
        {
            _context = context;
        }

        // GET: HangHoas
        public async Task<IActionResult> Index(int page=1)
        {
            if (User.Identity.Name != admin)
            {
                return RedirectToAction("Index", "TrangChus");
            }
            var query = _context.HangHoas.Include(h => h.Loai).AsNoTracking().OrderBy(p => p.MaHH);
            var model = await PagingList.CreateAsync(query, 10, page);
            return View(model);
        }
       


        // GET: HangHoas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas
                .Include(h => h.Loai)
                .FirstOrDefaultAsync(m => m.MaHH == id);
            if (hangHoa == null)
            {
                return NotFound();
            }

            return View(hangHoa);
        }

        // GET: HangHoas/Create
        public IActionResult Create()
        {
            if (User.Identity.Name != admin)
            {
                return RedirectToAction("Index", "TrangChus");
            }
            ViewData["MaLoai"] = new SelectList(_context.loais, "MaLoai", "TenLoai");
            return View();
        }

        // POST: HangHoas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHH,TenHH,Hinh,MoTa,DonGia,SoLuong,MaLoai,NgayDang,NoiBat")]  HangHoa hangHoa, IFormFile fHinh)
        {
          
            if (fHinh != null)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(),
                @"wwwroot\Hinh", fHinh.FileName);
                using (var file = new FileStream(path, FileMode.Create))
                {
                    await fHinh.CopyToAsync(file);
                }
                hangHoa.Hinh = fHinh.FileName;
            
            }
            hangHoa.NgayDang = DateTime.Now;
        
            if (ModelState.IsValid)
            {
               
                _context.Add(hangHoa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoai"] = new SelectList(_context.loais, "MaLoai", "TenLoai", hangHoa.MaLoai);
            return View(hangHoa);
        }

        //public IActionResult Edit(int? id)
        //{
        //    HangHoa lo = new HangHoa();
        //    if (id.HasValue && id.Value != 0)
        //    {
        //        lo = _context.HangHoas.SingleOrDefault(p => p.MaHH == id);
        //    }
        //    return PartialView("_Edit", lo);
        //}

       // GET: HangHoas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas.FindAsync(id);
            if (hangHoa == null)
            {
                return NotFound();
            }
            ViewData["MaLoai"] = new SelectList(_context.loais, "MaLoai", "TenLoai", hangHoa.MaLoai);
            return View(hangHoa);
        }

        // POST: HangHoas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, HangHoa model,
IFormFile fHinh)
        {
            if (fHinh != null)
            {
                //upload file
                var path = Path.Combine(Directory.GetCurrentDirectory(),
               @"wwwroot\Hinh", fHinh.FileName);
                using (var file = new FileStream(path, FileMode.Create))
                {
                    await fHinh.CopyToAsync(file);
                }
                model.Hinh = fHinh.FileName;
            }
            if (id.HasValue && id.Value > 0)
            {
                _context.Update(model);
            }
            else
            {
                _context.Add(model);
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: HangHoas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas
                .Include(h => h.Loai)
                .FirstOrDefaultAsync(m => m.MaHH == id);
            if (hangHoa == null)
            {
                return NotFound();
            }

            return View(hangHoa);
        }

        // POST: HangHoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hangHoa = await _context.HangHoas.FindAsync(id);
            _context.HangHoas.Remove(hangHoa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HangHoaExists(int id)
        {
            return _context.HangHoas.Any(e => e.MaHH == id);
        }
        public IActionResult Search()
        {
           
            return View();
        }
        [HttpPost]

        public IActionResult Search(string Keyword = "")
        {
            var data = _context.HangHoas.Where(p => p.TenHH.Contains(Keyword))
          .Include(p => p.Loai)
            .ToList();
            return PartialView("_SearchPartial", data);
        }
        public IActionResult JSONSearch(string Name = "", double? From = 0,
        double? To = double.MaxValue)
        {
            var data = _context.HangHoas.Where(p => p.TenHH.Contains(Name) &&
           p.DonGia >= From && p.DonGia <= To)
            .Select(p => new {
                TenHH = p.TenHH,
                DonGia = p.DonGia,
                Loai = p.Loai.TenLoai
            });
            return Json(data);
        }
        public IActionResult TimKiem()
        {
            return View();
        }
        
    }
}

WebBanHang/Views/HangHoas/Create.cshtml
@model WebBanHang.Models.HangHoa

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/Components/_AdminPage.cshtml";
}

<h2>Create</h2>

<h4>HangHoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post"
              enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenHH" class="control-label"></label>
                <input asp-for="TenHH" class="form-control" />
                <span asp-validation-for="TenHH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hinh" class="control-label"></label>

                <input type="file" name="fHinh" class="form-control" />
                <span asp-validation-for="Hinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label"></label>
                <textarea asp-for="MoTa" class="form-control" rows="6" style="resize: none" ></textarea>
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DonGia" class="control-label"></label>
                <input asp-for="DonGia" class="form-control" />
                <span asp-validation-for="DonGia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuong" class="control-label"></label>
                <input asp-for="SoLuong" class="form-control" />
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLoai" class="control-label"></label>
                <select asp-for="MaLoai" class="form-control" asp-items="ViewBag.MaLoai"></select>
            </div>
            <div class="form-group">
                <label asp-for="GiamGia" class="control-label"></label>
                <input asp-for="GiamGia" class="form-control" />%
                <span asp-validation-for="GiamGia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="NoiBat" type="checkbox">  Sản phẩm nổi bật
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebBanHang/Views/HangHoas/Delete.cshtml
@model WebBanHang.Models.HangHoa

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/Components/_AdminPage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HangHoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenHH)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TenHH)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Hinh)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hinh)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Loai)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Loai.TenLoai)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaHH" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebBanHang/Views/HangHoas/Details.cshtml
@model WebBanHang.Models.HangHoa

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/Components/_AdminPage.cshtml";
}

<h2>Details</h2>

<div>
    <h4>HangHoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaHH)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaHH)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TenHH)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TenHH)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Hinh)
        </dt>
        <dd>
            <img src="~/Hinh/@Html.DisplayFor(model => model.Hinh)" width="200" height="200" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NgayDang)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NgayDang)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GiamGia)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GiamGia)%
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Loai)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Loai.TenLoai)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoiBat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoiBat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DaMua)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DaMua)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MaHH">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebBanHang/Views/HangHoas/Edit.cshtml
@model WebBanHang.Models.HangHoa

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/Components/_AdminPage.cshtml";
}

<h2>Edit</h2>

<h4>HangHoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@Model.MaHH" method="post"
              enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaHH" />
            <div class="form-group">
                <label asp-for="TenHH" class="control-label"></label>
                <input asp-for="TenHH" class="form-control" />
                <span asp-validation-for="TenHH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hinh" class="control-label col-lg-3 colsm-3"></label>
                <div class="col-lg-9">
                    <input name="Hinh" class="hidden" value="@Model.Hinh" />
                    <img src="~/Hinh/@Model.Hinh" />
                    <input type="file" name="fHinh" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label"></label>
                <textarea asp-for="MoTa" class="form-control" rows="6" style="resize: none"></textarea>
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DonGia" class="control-label"></label>
                <input asp-for="DonGia" class="form-control" />
                <span asp-validation-for="DonGia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiamGia" class="control-label"></label>
                <input asp-for="GiamGia" class="form-control" />
                <span asp-validation-for="GiamGia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuong" class="control-label"></label>
                <input asp-for="SoLuong" class="form-control" />
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLoai" class="control-label"></label>
                <select asp-for="MaLoai" class="form-control" asp-items="ViewBag.MaLoai"></select>
                <span asp-validation-for="MaLoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayDang" class="control-label"></label>
                <input asp-for="NgayDang" class="form-control" />
                <span asp-validation-for="NgayDang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="NoiBat" type="checkbox"> Sản phẩm nổi bật
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebBanHang/Views/HangHoas/Index.cshtml
@model ReflectionIT.Mvc.Paging.IPagingList<WebBanHang.Models.HangHoa>

@using ReflectionIT.Mvc.Paging
@addTagHelper *,ReflectionIT.Mvc.Paging
@{
    ViewData["Title"] = "Index";
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "~/Views/Shared/Components/_AdminPage.cshtml";
}

<h2>Index</h2>
<nav aria-label="HangHoa Paging">
    @await this.Component.InvokeAsync("Pager",new {pagingList= this.Model })
</nav>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Tên Hàng
            </th>
            <th>
                Ảnh
            </th>
            <th>
                Giá
            </th>
            <th>
               Giảm Giá
            </th>
            <th>
                Số Lượng
            </th>
            <th>
                Loại
            </th>
            <th>
                Ngày Đăng
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenHH)
            </td>
            <td>
                <img src="~/Hinh/@item.Hinh" width="100" height="100" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonGia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiamGia)%
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Loai.TenLoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDang)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MaHH">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MaHH">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MaHH">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebBanHang/Views/HangHoas/Search.cshtml
@{
    ViewData["Title"] = "Search";
    Layout = "~/Views/Shared/Components/_AdminPage.cshtml";
}
<h3><a asp-action="TimKiem" asp-controller="HangHoas">Tìm kiếm nâng cao</a></h3>
<h2>Tìm kiếm hàng hóa</h2>



<input type="text" id="txtSearch" placeholder="Input here.." />
<div id="result"></div>

@section Scripts{
    <script>
        //gắn hàm xử lý cho sự kiện nhấn phím trên textbox
        $("#txtSearch").keyup(function () {
            $.ajax({
                url: "/HangHoas/Search",
                type: "POST",
                data: { "Keyword": $(this).val() },
                success: function (data) {
                    $("#result").html(data);
                }
            });
        });
    </script>
}
<script>
    $("#btnTim").click(function () {
        var ten = $("#txtTen").val().trim();
        var giaTu = $("#txtGiaTu").val();
        var giaDen = $("#txtGiaDen").val();
        $.ajax({
            url: "/HangHoas/JSONSearch",
            type: "GET",
            data: {
                "Name": ten, "From": giaTu, "To": giaDen
            },
            success: function (data) {
                //console.log(data);
                $("#content").html("");
                //duyệt qua từng phần tử của tập kết quả
                $(data).each(function (index, value) {
                    //tạo thẻ tr
                    var tr = $("<tr />");
                    //tạo nội dung cho thẻ tr
                    $("<td/>").html(index + 1).appendTo(tr);
                    $("<td/>").html(value.TenHH).appendTo(tr);
                    $("<td/>").html(value.DonGia).appendTo(tr);
                    $("<td/>").html(value.Loai).appendTo(tr);
                    //thêm vào tbody
                    tr.appendTo("#content");
                });
            }
        });
    });
</script>

WebBanHang/Views/HangHoas/TimKiem.cshtml
@{
    ViewData["Title"] = "Advance Search";
    Layout = "~/Views/Shared/Components/_AdminPage.cshtml";
}

<h2>Advance Search</h2>

<input type="text" id="txtTen" placeholder="Nhập tên" /><br />
Giá từ <input type="number" min="0" id="txtGiaTu" />
đến <input type="number" min="0" id="txtGiaDen" />
<input type="button" id="btnTim" value="Tìm" />
<h2>Kết quả</h2>
<table class="table table-condensed">
    <thead>
        <tr>
            <th>STT</th>
            <th>Tên hàng hóa</th>
            <th>Đơn giá</th>
            <th>Loại</th>
        </tr>
    </thead>
    <tbody id="content"></tbody>
</table>
@section Scripts{
    <script>
        $("#btnTim").click(function () {
            var ten = $("#txtTen").val().trim();
            var giaTu = $("#txtGiaTu").val();
            var giaDen = $("#txtGiaDen").val();
            $.ajax({
                url: "/HangHoas/JSONSearch",
                type: "GET",
                data: {
                    "Name": ten, "From": giaTu, "To": giaDen
                },
                success: function (data) {
                    //console.log(data);
                    $("#content").html("");
                    //duyệt qua từng phần tử của tập kết quả
                    $(data).each(function (index, value) {
                        //tạo thẻ tr
                        var tr = $("<tr />");
                        //tạo nội dung cho thẻ tr
                        $("<td/>").html(index + 1).appendTo(tr);
                        $("<td/>").html(value.tenHH).appendTo(tr);
                        $("<td/>").html(value.donGia).appendTo(tr);
                        $("<td/>").html(value.loai).appendTo(tr);
                        //thêm vào tbody
                        tr.appendTo("#content");
                    });
                }
            });
        });
    </script>
}

WebBanHang/Views/HangHoas/_SearchPartial.cshtml
@model IEnumerable<WebBanHang.Models.HangHoa>
@{
    ViewData["Title"] = "_SearchPartial";
}

<h2>Kết quả</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenHH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MoTa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DonGia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoLuong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Loai)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TenHH)
                </td>
                <td>
                    <img src="~/Hinh/@item.Hinh" width="50" height="50" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MoTa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DonGia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoLuong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Loai.TenLoai)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.MaHH">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.MaHH">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.MaHH">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>